### ISSUE TITLE
Exception on extension registration

### ISSUE THREAD

**Issue by davidorme** [jobovy/sphinx-astrorefs#3]
Hi there,

I'm trying to use this with a project and I'm getting an error when I try and build. `make` is the standard `sphinx-quickstart` make file. I'm running `sphinx==3.2.1` in Python 3.7.7 on Mac OS X.

```sh
$ make html 
Running Sphinx v3.2.1
Registering astro-style pybtex formatting...

Extension error:
Handler <function setup_latex at 0x10c4aa7a0> for event 'config-inited' threw an exception (exception: 'preamble')
make: *** [html] Error 2
```

Any idea?

Many thanks,
David

**Comment by jobovy** [comment]
Hi David,

Apologies for the slow reply! I honestly have no idea what this could be about. The 'astro-style pybtex' registration just defines a new pybtex citation style and that code doesn't mention 'preamble' at all. I suspect that this may have to do with your LaTeX setup in your `conf.py`, which may have an error in the preamble section. Does your sphinx build run successfully if you don't include this extension?

**Comment by davidorme** [comment]
It does build without `astrof-refs`. My extensions look like this:

``` python
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.napoleon',
              'sphinx.ext.mathjax',
              'sphinx.ext.autosummary',
              'sphinxcontrib.bibtex',
              #'sphinx_astrorefs',  # Gives author year references
              'sphinx_rtd_theme',
              'recommonmark'
              ]
```

I thought for a second that I'd botched the name of the style, but it isn't even getting to my bibliography directive.

**Comment by jobovy** [comment]
Okay, that's weird! There must be some weird interaction between `sphinx-astrorefs` and your setup. I think the only way forward would be for you to post a minimal version of your project that has the issue, so we can run that and look at it. But I should warn you that I don't have very much time to look into this currently...

**Comment by davidorme** [comment]
Thanks @jobovy. It isn't exactly minimal, but it isn't a huge project at the moment:

https://github.com/davidorme/pypmodel

Completely understand about time - it would be lovely to get it working but if I'm forced to use the [nastyref] style, I'll still have a bibliography.

**Comment by jobovy** [comment]
Hi @davidorme -- Okay, I looked into this and it seems like the issue might be that you didn't have a custom LaTeX `preamble` in your `conf.py`, which caused a problem (I guess I've only ever tested it with custom preambles). I pushed a possible fix, could you use the `master` branch and test whether it works for you? I can't get your documentation to build locally (the extension registration now works for me, but I'm getting some `autodoc` errors that are probably related to me not having the correct setup; I get them with and without the `sphinx_astrorefs` extension).

**Comment by davidorme** [comment]
Hi @jobovy. Yup - that has done the trick and it now runs. Many thanks.

My remaining issue is that I'm using Myst markdown notebooks and Jupyter Book to have run-able code in my  documentation and I think that is overriding the citation style. That isn't an `sphinx-astrorefs` problem, but I'm going to raise it with the Jupyter Book developers, so you will see a mention from that.

**Comment by jobovy** [comment]
Okay, great. I'll release a new version soon then so you can grab it off pip (that would be easier for readthedocs).

I use [`nbsphinx`](https://github.com/spatialaudio/nbsphinx) to include jupyter notebooks in Sphinx and that seems to work fine, but I think MyST in principle should work as well and may be better. Note that with `sphinxcontrib-bibtex` version >= 2, you now have to run Sphinx twice to get the references right; that might be part of your issue?

**Comment by davidorme** [comment]
That was the issue - running it twice fixed it. 

I'm pulling in function descriptions using `autodoc` and those aren't getting formatted in astrostyle - one of the difficulties with `autodoc` is that it is tied to `rst`, so I suspect that it a Myst issue.

**Comment by jobovy** [comment]
I released a new version that includes the fix, so hopefully that fully resolves this issue now.
